trigger:
- main

jobs:
  # https://github.com/actions/python-versions/blob/main/versions-manifest.json
  - job: linux
    pool:
      vmImage: 'ubuntu-latest'
    strategy:
      matrix:
        # Python 3.6 is not available on ubuntu 22.04 (latest)
        #Python36:
          # specifying the vmImage here does not work
          #vmImage: 'ubuntu-20.4'
          #python.version: '3.6'
        Python37:
          python.version: '3.7'
        Python38:
          python.version: '3.8'
        Python39:
          python.version: '3.9'
        Python310:
          python.version: '3.10'
        Python311:
          python.version: '3.11'
        #Python312:
          # requires allowUnstable
          # as of 3.12.0-alpha.3, no pandas or numpy wheels, pandas build fails after 19 minutes
          #python.version: '3.12-dev'

    steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '$(python.version)'
        allowUnstable: true
      displayName: 'Use Python $(python.version)'

    - script: |
        python -m pip install --upgrade pip
        pip install . .[test]
      displayName: 'Install dependencies'

    - script: |
        pip install pytest pytest-azurepipelines
        make test_coverage
      displayName: 'pytest'

    - script: |
        pip install coveralls
        export CIRCLE_BRANCH=$BUILD_SOURCEBRANCH
        coveralls
      displayName: 'coveralls'
      env:
        CIRCLECI: 1
        CIRCLE_BUILD_NUM: $(Build.BuildNumber)
        COVERALLS_REPO_TOKEN: $(coveralls_repo_token)

  - job: macos
    pool:
      vmImage: 'macOS-latest'
    strategy:
      matrix:
        Python38:
          python.version: '3.8'

    steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '$(python.version)'
      displayName: 'Use Python $(python.version)'

    - script: |
        python -m pip install --upgrade pip
        pip install . .[test]
      displayName: 'Install dependencies'

    - script: |
        pip install pytest pytest-azurepipelines
        make test_coverage
      displayName: 'pytest'

    - script: |
        pip install coveralls
        export CIRCLE_BRANCH=$BUILD_SOURCEBRANCH
        coveralls
      displayName: 'coveralls'
      env:
        CIRCLECI: 1
        CIRCLE_BUILD_NUM: $(Build.BuildNumber)
        COVERALLS_REPO_TOKEN: $(coveralls_repo_token)

